# Generated by Django 2.2.12 on 2020-04-16 04:52

from django.db import migrations, models
import django.db.models.deletion
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания статьи')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок статьи')),
                ('content', models.TextField(verbose_name='Содержание (текст) статьи')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео (одно)')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='ArticleKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=100, verbose_name='Тип статьи')),
            ],
            options={
                'verbose_name': 'Тип статьи',
                'verbose_name_plural': 'Типы статей',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование партнёра')),
                ('logo', models.ImageField(blank=True, upload_to='images/logos/', verbose_name='Логотип')),
                ('important', models.BooleanField(default=False, verbose_name='Отобразить в блоке важных')),
                ('site', models.CharField(blank=True, max_length=100, verbose_name='Сайт')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Краткое описание')),
                ('activity', models.CharField(blank=True, max_length=250, verbose_name='Сфера деятельности')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Адрес')),
                ('phones', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=25), blank=True, size=None, verbose_name='Телефон/телефоны')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='', verbose_name='Фотографии (одна или несколько)')),
                ('article', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='front.Article', verbose_name='Статья')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='kind',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='front.ArticleKind', verbose_name='Тип статьи'),
        ),
    ]
