# Generated by Django 2.2.12 on 2020-04-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20200417_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка статьи'),
        ),
    ]
