# Generated by Django 2.2.12 on 2020-04-17 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20200417_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover',
            field=models.FileField(blank=True, upload_to='images/covers/', verbose_name='Обложка статьи'),
        ),
    ]
