# Generated by Django 2.2.12 on 2020-04-17 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_article_videolink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='video',
        ),
    ]
