# Generated by Django 2.2.12 on 2020-04-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_remove_article_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='videocover',
            field=models.FileField(blank=True, upload_to='images/covers/', verbose_name='Обложка видео'),
        ),
    ]
