# Generated by Django 2.2.12 on 2020-04-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_article_videocover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, verbose_name='Период/год')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование файла')),
                ('file', models.FileField(blank=True, upload_to='files/', verbose_name='Файл с отчетом')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчеты',
            },
        ),
    ]
