# Generated by Django 2.2.12 on 2020-04-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0011_auto_20200422_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='metadescr',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta Description'),
        ),
        migrations.AddField(
            model_name='settings',
            name='metakeywords',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Meta Keyword'),
        ),
    ]
