# Generated by Django 2.2.12 on 2020-04-24 04:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0012_auto_20200422_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_publish',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 24, 11, 8, 10, 488406), verbose_name='Дата публикации статьи'),
        ),
    ]
