# Generated by Django 2.2.12 on 2020-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0014_auto_20200424_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date_publish',
            field=models.DateField(verbose_name='Дата публикации статьи'),
        ),
    ]
