# Generated by Django 2.2.12 on 2020-04-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_auto_20200428_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_publish'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='User id аккаунта в instagram'),
        ),
        migrations.AddField(
            model_name='settings',
            name='rapidapi_host',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='x-rapidapi-host в headers'),
        ),
        migrations.AddField(
            model_name='settings',
            name='rapidapi_key',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='x-rapidapi-key в headers'),
        ),
    ]
