# Generated by Django 2.2.12 on 2020-04-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_auto_20200429_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='rapidapi_host',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='rapidapi_key',
        ),
    ]
