# Generated by Django 2.2.12 on 2020-04-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0019_auto_20200429_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rapidapi_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Адрес запроса к rapidapi'),
        ),
    ]
