# Generated by Django 2.2.12 on 2020-04-29 04:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0020_settings_rapidapi_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rapidapi_header',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='Заголовок запроса к rapidapi'),
        ),
    ]
