# Generated by Django 2.2.12 on 2020-04-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0021_settings_rapidapi_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='instagram_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='id статьи в instagram'),
        ),
    ]
