# Generated by Django 2.2.12 on 2020-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0022_article_instagram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_cover',
            field=models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка статьи по умолчанию'),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_videocover',
            field=models.ImageField(blank=True, upload_to='images/covers/', verbose_name='Обложка видео по умолчанию'),
        ),
    ]
