# Generated by Django 2.2.12 on 2020-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0023_auto_20200429_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='videolink',
            field=models.TextField(blank=True, null=True, verbose_name='Ссылка на видео (одно)'),
        ),
    ]
