# Generated by Django 2.2.12 on 2024-01-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0024_auto_20200502_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vk_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='settings',
            name='vk_token',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='instagram_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='id статьи в instagram'),
        ),
    ]
