# Generated by Django 2.2.12 on 2024-01-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0025_auto_20240113_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='vk_start',
            field=models.DateField(default='2022-12-02'),
        ),
    ]
