# Generated by Django 2.2.12 on 2024-01-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0026_settings_vk_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='vk_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
