# Generated by Django 2.2.12 on 2020-04-14 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200409_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='important',
            field=models.BooleanField(default=False, verbose_name='Отобразить в блоке важных'),
        ),
    ]
