[program:dom_miloserdia_api]
command=/venv/dom_miloserdia_api/bin/gunicorn dom_miloserdia_api.wsgi:application --bind=127.0.0.1:8040 --workers=2 --pid=/tmp/dom_miloserdia_api.pid --log-file=/www/dom_miloserdia_api/gunicorn.log --reload
process_name=%(program_name)s
redirect_stderr=true
directory=/www/dom_miloserdia_api/
umask=022
autostart=true
autorestart=true
startsecs=10
startretries=3
exitcodes=0,2
stopsignal=TERM
stopwaitsecs=10
user=ae
stdout_logfile=/www/dom_miloserdia_api/logs/django_stdout.log
stderr_logfile=/www/dom_miloserdia_api/logs/django_stderr.log

[program:dom_miloserdia_tasks]
# command=/venv/dom_miloserdia_api/bin/celery worker --scheduler django -B -A dom_miloserdia_api --loglevel=INFO -Q default -E  --concurrency=1
command=/venv/dom_miloserdia_api/bin/python manage.py qcluster
directory=/www/dom_miloserdia_api
process_name=%(program_name)s
autostart=true
autorestart=true
user=ae
stdout_logfile=/www/dom_miloserdia_api/logs/tasks_stdout.log
stderr_logfile=/www/dom_miloserdia_api/logs/tasks_stderr.log
