# Generated by Django 2.2.12 on 2020-04-29 04:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0016_auto_20200428_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_publish'], 'verbose_name': 'Статья', 'verbose_name_plural': '2 - Статьи'},
        ),
        migrations.AlterModelOptions(
            name='articlekind',
            options={'verbose_name': 'Тип статьи', 'verbose_name_plural': '3 - Типы статей'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['title'], 'verbose_name': 'Партнёр', 'verbose_name_plural': '1 - Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'verbose_name': 'Отчёт', 'verbose_name_plural': '4 - Отчеты'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройки', 'verbose_name_plural': '5 - Настройки'},
        ),
        migrations.AddField(
            model_name='settings',
            name='instagram_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='User id аккаунта в instagram'),
        ),
        migrations.AddField(
            model_name='settings',
            name='rapidapi_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=100, null=True, verbose_name='Заголовок запроса к rapidapi'),
        ),
        migrations.AddField(
            model_name='settings',
            name='rapidapi_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Адрес запроса к rapidapi'),
        ),
    ]
