# Generated by Django 2.2.12 on 2020-04-29 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0017_auto_20200429_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='instagram_id',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='rapidapi_headers',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='rapidapi_url',
        ),
    ]
