# Generated by Django 2.2.12 on 2020-04-29 04:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0018_auto_20200429_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='rapidapi_url',
            field=models.URLField(blank=True, default='', max_length=100, null=True, verbose_name='Адрес запроса к rapidapi'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='rapidapi_headers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, max_length=100, null=True, verbose_name='Заголовок запроса к rapidapi'),
        ),
    ]
